### ISSUE TITLE
Svar_DB not connected in Svar_DB::is_registered_id()

### ISSUE THREAD

**Issue by fourier** [lokedhs/gnu-apl-mode#11]
I got a following string every time I run gnu-apl with SVN version (r662) of GNU APL on OSX. What could it mean? Any way to get rid of it?

**Comment by lokedhs** [comment]
I've had that much longer on some machines only. I did some research into
this over a year ago but I don't remember the details. It had something to
do with the network configuration on the specific machine.

Regards,
Elias

**Comment by fourier** [comment]
Ok, so if it is not harmful I'll close the issue.

**Comment by lokedhs** [comment]
Correct. As long as you are not using AP210, it's completely harmless. You
can completely disable AP210 by using the flag --noSV

Regards,
Elias
