### ISSUE TITLE
Other backends?

### ISSUE THREAD

**Issue by fourier** [lokedhs/gnu-apl-mode#12]
Is where a possibility to add other backend, for example Dyalog APL?

**Comment by lokedhs** [comment]
It's possible, but probably not very easy. None of the code was written with the intention of being usable with other APL's. It would probably be easier to write a new mode for those APL's (possibly by re-using some of the code).

**Comment by fourier** [comment]
Ok, I'll keep that in mind when Dyalog releases protocol details for their RIDE.
