### ISSUE TITLE
FR: Make modifier key configurable

### ISSUE THREAD

**Issue by Fabricationatorishnicatorist** [lokedhs/gnu-apl-mode#13]
First of all, thanks for creating this. I'm new to APL and this is so much better then typing in unicode hex codes into urxvt... :)

I use a tiling window manager and <kbd>Super</kbd> is dedicated to it. That fact is stored more deeply in my muscle memory than most generic human motor skills. I switched `gnu-apl-mode`
to employ the unused <kbd>Hyper</kbd> key but this required editing the code and recompiling and will get clobbered next time you push an update to MELPA.

Would you please make the hotkey configurable via a customization option?

**Comment by lokedhs** [comment]
The way it's built right now isn't really very customisable. I have been
thinking of better ways to handle the keymaps. I'll take another look and
see what I can do.

**Comment by Fabricationatorishnicatorist** [comment]
I appreciate it, thank you.

**Comment by grettke** [comment]
Hi @lokedhs . Here is a patch that does **not** work to provide a customizable keymap prefix https://github.com/grettke/gnu-apl-mode/commit/2183d7a55ff474bbbcfe4c7d3dcbab1b0849b62f . Can you tell me more about the approach for the keybindings (why it isn't customizable)?

**Comment by lokedhs** [comment]
Hello Grant,

I'm not entirely sure what it is you're trying to do that won't work. Are
you perhaps changing the value of gnu-apl-interactive-mode-map-prefix after
the file was loaded? If so, you must also regenerate the value of
gnu-apl-interactive-mode-map (as well as gnu-apl-mode-map).

Regards,
Elias

**Comment by grettke** [comment]
@lokedhs Hi Elias. You are right. The code is fine. I made a mistake using `customize'. When you set variables used by customize, you have to set them /before/ you load a library that uses customize. So even though I set the variables, they weren't considered. Is that what you meant by regenerating?

Either way: I will submit this as a patch because it does work as expected.

**Comment by lokedhs** [comment]
Thanks,

I do want you to update it such that you can go into customize and have the
change immediately update the existing keymap.

Customize has a feature that allows you to configure a function to be
called when a customisable setting is changed. When this is done the keymap
has to be rebuilt.

Regards,
Elias

**Comment by grettke** [comment]
Hi Elias,

You are welcome. Gotcha. Will do.

Sincerely,

Grant Rettke

**Comment by lokedhs** [comment]
I have merged the fix as of 88070ad09670599da0750c6209e819b97ed2e821

**Comment by grettke** [comment]
Thank you @lokedhs .

**Comment by lokedhs** [comment]
I just noticed something. Your fix only changes the keymap for interactive mode, not the one used when editing .apl files.

**Comment by lokedhs** [comment]
Could you fix that too?

**Comment by grettke** [comment]
I had tested both interactive and editing mode.

Let me look again and test it out.

**Comment by lokedhs** [comment]
In that case, it's OK. I haven't tested editing mode. I just had that impression by looking at the code just now. 

The first thing that struck me was that you had put the functions and variables in the file gnu-apl-interactive.el, and I didn't see any references to the other keymap in the diff (I could have misread).

**Comment by grettke** [comment]
Gotcha.

I was thinking that since the edit features were defined in gnu-apl-mode.el https://github.com/lokedhs/gnu-apl-mode/blob/master/gnu-apl-mode.el#L228-L256 that I should put them there and keep the interactive features in that file https://github.com/lokedhs/gnu-apl-mode/blob/master/gnu-apl-interactive.el#L197-L229 .

**Comment by lokedhs** [comment]
Does the fix made by @grettke solve this issue? Can we close it?

**Comment by grettke** [comment]
Yes it solves it because you can use Hyper like this:

`(setq gnu-apl-mode-map-prefix "H-")`
`(setq gnu-apl-interactive-mode-map-prefix "H-")`

or use Customize.
