### ISSUE TITLE
Clobbering of user-reserved keybindings

### ISSUE THREAD

**Issue by larsbrinkhoff** [lokedhs/gnu-apl-mode#18]
GNU APL Mode adds a keybinding for `C-c r`:

https://github.com/lokedhs/gnu-apl-mode/blob/2118e0ef1aabecd2745709ad0eb9e4a1129ce9d4/gnu-apl-mode.el#L230

This is contrary to Emacs conventions:

> Don’t define C-c *letter* as a key in Lisp programs. Sequences consisting of C-c and a letter (either upper or lower case) are reserved for users; they are the **only** sequences reserved for users, so do not block them. 

https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html

**Comment by lokedhs** [comment]
Point taken. Most of the keybindings chosen are pretty bad in fact.
