### ISSUE TITLE
New help functionality was not merged properly

### ISSUE THREAD

**Issue by lokedhs** [lokedhs/gnu-apl-mode#29]
After merging pull request #26 as of change 1fce747e48290549c859de7b15e6efc351d60861 the updated files are not in the repository. They can be seen from the Github user interface.

This might be some feature of git that I am unaware of, but I would appreciate it if @fourier could have a look at this.

**Comment by fourier** [comment]
Please check the pull request https://github.com/lokedhs/gnu-apl-mode/pull/30
As for elisp part it looks ok to me.

**Comment by lokedhs** [comment]
I have merged it, and made some fixes. @fourier can you test the current version?
