### ISSUE TITLE
Will not run any hooks on startup

### ISSUE THREAD

**Issue by equwal** [lokedhs/gnu-apl-mode#35]
In an attempt to disable smartparens in GNUAPL
```elisp
(defun smartparens-off ()
  (interactive)
  (smartparens-mode 0))
(add-hook 'gnu-apl-mode-hook 'smartparens-off)
```
But still it is enabled! I can turn it off by evaluating it outside of a hook (smartparens-off).
Also try `(add-hook 'gnu-apl-mode-hook 'fundamental-mode)` and watch it not work on GNU Emacs 27.0.50

**Comment by lokedhs** [comment]
The mode used in the interactive session is called `gnu-apl-interactive-mode`. The other mode is used for buffers editing `.apl` files.
